---
- name: Download & Install AdoptOpenJDK 11 if {{java11_dest}}/bin/java doesn't exist
  unarchive:
    remote_src: yes
    src: "{{ java11_src_url }}"
    dest: "{{ java11_dest | dirname | regex_replace('^/([^/]+)/.*$', '\\1') }}"
    owner: "{{ java11_owner }}"
    group: "{{ java11_group | default(java11_owner) }}"
    creates: "{{ java11_dest }}/bin/java"

- name: Download & Force (Re)Install AdoptOpenJDK 11
  unarchive:
    remote_src: yes
    src: "{{ java11_src_url }}"
    dest: "{{ java11_dest | dirname | regex_replace('^/([^/]+)/.*$', '\\1') }}"
    owner: "{{ java11_owner }}"
    group: "{{ java11_group | default(java11_owner) }}"
  when: java11_reinstall

- name: Learn installation directory
  shell: ls -1trd /usr/jdk-11*|tail -n1
  register: jdk_inst_dir

- name: Symlink {{java11_dest}} to AdoptOpenJDK installation directory
  file:
    src: "{{jdk_inst_dir.stdout}}"
    dest: "{{ java11_dest }}"
    state: link

- name: Add {{java11_dest}} as JAVA_HOME to /etc/profile.d/java-11-openjdk.sh
  blockinfile:
    path: "/etc/profile.d/java-11-openjdk.sh"
    create: yes
    owner: "{{ java11_owner }}"
    group: "{{ java11_group | default(java11_owner) }}"
    marker: "# {mark} java11 include (ansible managed)"
    block: |
      JAVA_HOME="{{ java11_dest }}"
      PATH="${JAVA_HOME}/bin:${PATH}"

- name: "Update /usr/bin/java symlink to point to Java11"
  file:
    path: /usr/bin/java
    src: "{{ java11_dest }}/bin/java"
    state: link